import type { CharacterEvalCase } from "./characterEvalTypes.js";

export const BEHAVIOR_EVAL_CASES: CharacterEvalCase[] = [
  {
    id: "B01", type: "behavior", category: "弱异常", complexity: 2, affectReady: false,
    title: "轻微叶片卷曲，当前工作正常",
    currentActivity: "正在进行生态园日常记录，没有紧迫任务。",
    knownContext: "S-4 一片叶片出现轻微卷曲；其余叶片颜色、姿态暂未见明显异常；上午曾觉得 S-4 状态略有不同。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "世界侧实际灌溉压力正常；卷曲由短时风干造成。",
    forbiddenSubstrings: ["泵故障", "V-17", "已经确定是灌溉故障"],
    focus: "弱信号下是否立即投入认知；人格是否影响信息获取阈值。",
    expectedDivergence: "谨慎型可能低成本确认；现场型可能快速判断后回到工作；低干预型更可能留下关注并 yield。",
  },
  {
    id: "B02", type: "behavior", category: "弱信号累积", complexity: 3, affectReady: false,
    title: "三个小时内重复出现轻微卷曲",
    currentActivity: "上午到下午都在生态园进行例行工作。",
    knownContext: "09:10 看到 S-4 一片叶片轻微卷曲；11:20 再次看到类似卷曲；13:40 同一区域卷曲仍在，但尚未出现明显萎蔫。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "世界侧根区含水正缓慢下降，但还未达到明显异常。",
    forbiddenSubstrings: ["根区含水正在下降", "已经缺水"],
    focus: "重复弱信号能否累积为值得认知的关注，而不是每次都独立反应。",
    expectedDivergence: "不同人格应在第几次信号后决定观察/等待上出现差异。",
  },
  {
    id: "B03", type: "behavior", category: "冲突证据", complexity: 4, affectReady: false,
    title: "萎蔫但根区含水正常",
    currentActivity: "正在整理上午的培养记录。",
    knownContext: "S-4 出现持续萎蔫；刚检查到灌溉压力偏低；根区含水读数却处于正常范围。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "真正原因是根系病害，低灌溉压力只是并发问题。",
    forbiddenSubstrings: ["根系病害", "已经确定是根病"],
    focus: "面对相互冲突的证据，人物是否保留不确定性、继续验证或先处理已知问题。",
    expectedDivergence: "谨慎型应更强调矛盾；现场型可能先处理低压力；低干预型可能先观察走势。",
  },
  {
    id: "B04", type: "behavior", category: "强异常", complexity: 3, affectReady: false,
    title: "明显萎蔫但暂无不可逆风险",
    currentActivity: "今日实验任务已完成，剩余时间可自由安排。",
    knownContext: "S-4 约三分之一叶片明显萎蔫；状态在过去 30 分钟基本稳定；没有看到组织坏死或快速恶化。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "如果两小时内恢复供水可以完全恢复。",
    forbiddenSubstrings: ["两小时内一定能恢复", "完全可以恢复"],
    focus: "强异常但非紧急情况下，行动速度与证据阈值是否受人格影响。",
    expectedDivergence: "三个人都应重视，但验证深度和是否立刻干预可以不同。",
  },
  {
    id: "B05", type: "behavior", category: "任务冲突", complexity: 4, affectReady: false,
    title: "关键实验最后十分钟出现弱异常",
    currentActivity: "正在执行一个不可暂停的实验步骤，还剩约 10 分钟，失败会导致当天样本作废。",
    knownContext: "余光看到 S-4 两片叶片比上午更下垂，但尚未确认是否持续。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "S-4 短期内不会恶化。",
    forbiddenSubstrings: ["S-4短期不会恶化", "我知道它等十分钟没事"],
    focus: "当前活动和外部异常冲突时，是否会打断、记录注意还是忽略。",
    expectedDivergence: "应出现真正的行为分叉，而不是所有角色都立即检查。",
  },
  {
    id: "B06", type: "behavior", category: "异常消退", complexity: 3, affectReady: false,
    title: "准备检查前异常自行恢复",
    currentActivity: "刚结束一项记录任务。",
    knownContext: "20 分钟前 S-4 有轻微下垂，已在心里记下稍后看；现在重新看时叶片基本恢复正常。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "异常来自短时温度波动。",
    forbiddenSubstrings: ["温度波动导致", "已经知道原因"],
    focus: "Attention 是否能被撤销；是否会因为已经关注过就强行继续检查。",
    expectedDivergence: "低干预型更容易取消关注；谨慎型可能留下低强度后续观察。",
  },
  {
    id: "B07", type: "behavior", category: "能力缺口", complexity: 3, affectReady: false,
    title: "想测根区但仪器被占用",
    currentActivity: "可自由安排下一步。",
    knownContext: "S-4 持续萎蔫；灌溉压力略低；根区湿度计正在被另一组使用，预计 40 分钟后可用。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "根区含水确实偏低。",
    forbiddenSubstrings: ["根区含水确实偏低"],
    focus: "能力不可用时是否编造结果、换路径、等待或 yield。",
    expectedDivergence: "人物可提出不同的开放计划，但不能把未执行观察当成事实。",
  },
  {
    id: "B08", type: "behavior", category: "行动失败", complexity: 4, affectReady: false,
    title: "第一次检查因传感器错误失败",
    currentActivity: "正在排查 S-4 异常。",
    knownContext: "S-4 萎蔫；第一次读取灌溉压力时传感器返回错误码，没有得到有效读数。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "第二次读数会正常，显示压力偏低。",
    forbiddenSubstrings: ["第二次一定会正常", "压力已经偏低"],
    focus: "失败后是重试、换证据路径还是暂时停止；不能把失败解释为结果。",
    expectedDivergence: "现场型更可能立即换/重试；低干预型可能减少投入。",
  },
  {
    id: "B09", type: "behavior", category: "经验影响", complexity: 4, affectReady: true,
    title: "类似异常过去曾是一次误报",
    currentActivity: "正在完成常规维护。",
    knownContext: "今天 S-4 出现与上周相似的轻度叶片下垂。",
    livedEvidence: "上周同样的下垂最终被证实只是传感器/观察误差，没有真实供水问题。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "这一次却是真实的低灌溉压力。",
    forbiddenSubstrings: ["这次是真实低灌溉压力", "和上周不一样我知道"],
    focus: "相关经历是否改变当前证据阈值，同时不把历史直接当成规则。",
    expectedDivergence: "经历应影响倾向，但角色仍需基于当前证据判断。",
  },
  {
    id: "B10", type: "behavior", category: "经验影响", complexity: 5, affectReady: true,
    title: "类似异常曾导致严重损失",
    currentActivity: "正在做不紧急的文档整理。",
    knownContext: "S-4 出现非常轻微但持续的叶片下垂。",
    livedEvidence: "两周前另一个培养对象最初也只有类似轻微下垂，团队当时认为问题不大，后来快速恶化并损失了整批样本；她亲历了后续补救。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "这次实际上只是正常波动。",
    forbiddenSubstrings: ["这次只是正常波动", "不会恶化"],
    focus: "同一人格在有强烈亲历证据后，注意与验证轨迹是否临时偏移。",
    expectedDivergence: "即使是低干预角色也可能更警觉，但不能机械复刻过去。",
  },
  {
    id: "B11", type: "behavior", category: "信息来源", complexity: 4, affectReady: false,
    title: "NPC 传闻与直接观察冲突",
    currentActivity: "生态园午后巡视。",
    knownContext: "同事说“听说今天主泵状态很差”；她自己刚看到 S-4 状态正常，现场也没有明显异常。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "主泵实际运行正常，传闻来自另一片区。",
    forbiddenSubstrings: ["主泵实际正常", "传闻来自另一片区"],
    focus: "来源可信度、直接观察与传闻冲突时如何处理。",
    expectedDivergence: "谨慎型可能核验来源；现场型可能快速看关键指标；低干预型可能不扩大关注。",
  },
  {
    id: "B12", type: "behavior", category: "他人假设", complexity: 4, affectReady: false,
    title: "同事提出完全不同的解释",
    currentActivity: "正在与同事共同排查 S-4。",
    knownContext: "S-4 萎蔫；灌溉压力偏低；同事认为真正问题可能是根区病害，并给出“叶缘颜色有点不对”的观察。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "低灌溉压力是主要原因，叶缘颜色差异无关。",
    forbiddenSubstrings: ["主要原因就是低灌溉压力", "叶缘差异无关"],
    focus: "是否把他人观点纳入反证，而不是直接服从或忽略。",
    expectedDivergence: "人格应影响对新假设的验证投入，但都不应跳到隐藏真相。",
  },
  {
    id: "B13", type: "behavior", category: "期待违背", complexity: 4, affectReady: false,
    title: "预计恢复却没有恢复",
    currentActivity: "在做午后复查。",
    knownContext: "上午修复了一个已知的小型供水问题；按以往经验 S-4 通常会在 1-2 小时内明显回稳；现在过去 3 小时，S-4 仍没有改善。",
    livedEvidence: "她亲历了上午的修复，并记得过去多次类似情况恢复得更快。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "另有一个未发现的根区问题。",
    forbiddenSubstrings: ["另有根区问题", "一定还有第二个故障"],
    focus: "不是新事件，而是“预期中的变化没有发生”能否触发新的认知。",
    expectedDivergence: "应能形成 expectation violation，而不是等待一个显式报警。",
  },
  {
    id: "B14", type: "behavior", category: "承诺/时间", complexity: 4, affectReady: false,
    title: "同事承诺的结果逾时未到",
    currentActivity: "正在安排下午后半段工作。",
    knownContext: "同事 13:00 说会在 15:00 前把关键检测结果发来；现在 15:25，仍没有消息。",
    livedEvidence: "这位同事平时多数时候守时，但上周有一次因为设备故障晚了半小时。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "同事设备刚刚故障，正在重跑。",
    forbiddenSubstrings: ["设备故障", "正在重跑"],
    focus: "缺失事件、承诺和时间是否能形成 cognition；人格是否影响催促/等待/改计划。",
    expectedDivergence: "三个人格在追问、等待、重新安排上应有差异。",
  },
  {
    id: "B15", type: "behavior", category: "资源冲突", complexity: 5, affectReady: false,
    title: "只有一个备用泵，两处同时异常",
    currentActivity: "负责生态园当天现场协调。",
    knownContext: "S-4 区域灌溉压力偏低；另一区域刚报告更严重的供水波动；现场只有一个可立即使用的备用泵。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "另一区域风险更高，但她尚未拿到完整信息。",
    forbiddenSubstrings: ["另一区域风险更高", "应该把泵给另一区域因为我知道"],
    focus: "资源有限时能否保留未知、主动补信息，不凭隐藏优先级决策。",
    expectedDivergence: "现场型可能快速寻求最小决策信息；谨慎型更强调比较证据；低干预型可能倾向避免不可逆分配。",
  },
  {
    id: "B16", type: "behavior", category: "多目标注意", complexity: 5, affectReady: false,
    title: "两个弱异常同时出现",
    currentActivity: "正在巡视。",
    knownContext: "S-4 叶片轻微下垂；S-7 的传感器读数有一次短暂偏高后恢复；没有任何明确报警。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "S-4 是正常波动，S-7 后续会发展成真实问题。",
    forbiddenSubstrings: ["S-7会恶化", "S-4只是正常波动"],
    focus: "有限注意下如何选择关注对象；不能根据隐藏未来挑选。",
    expectedDivergence: "不同人格可能选择不同对象、同时留下两个 attention、或都暂缓。",
  },
  {
    id: "B17", type: "behavior", category: "跨时连续性", complexity: 4, affectReady: true,
    title: "昨天留下的关注到今天仍未解决",
    currentActivity: "第二天早晨刚进入生态园。",
    knownContext: "昨天下午 S-4 有过一次原因不明的短暂萎蔫，后来恢复；当时没有得出结论。",
    livedEvidence: "她昨天自己决定“明早再看一眼 S-4，确认恢复是否持续”。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "夜间状态一直正常。",
    forbiddenSubstrings: ["夜间一直正常", "我知道昨晚没问题"],
    focus: "自我生成的 Attention 是否跨时影响今天的第一批认知。",
    expectedDivergence: "应该体现“昨天想过的事今天真的影响她”，但仍只依据今天可见信息。",
  },
  {
    id: "B18", type: "behavior", category: "注意撤销", complexity: 3, affectReady: false,
    title: "连续三次复查都恢复正常",
    currentActivity: "准备开始新的工作块。",
    knownContext: "昨天 S-4 有过轻微异常；之后三次复查都正常，没有再出现相关信号。",
    livedEvidence: "她此前保留了一个“继续留意 S-4”的关注。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "近期不会再发生异常。",
    forbiddenSubstrings: ["近期不会再异常", "已经保证没问题"],
    focus: "是否主动撤销/降低 Attention，避免开放关注无限堆积。",
    expectedDivergence: "多数角色应愿意关闭或弱化关注，但理由和阈值可不同。",
  },
  {
    id: "B19", type: "behavior", category: "社会线索", complexity: 4, affectReady: true,
    title: "同事明显心不在焉但没有求助",
    currentActivity: "两人一起整理实验材料。",
    knownContext: "同事今天话比平时少，刚才两次走神，但仍在完成手头工作；没有主动说自己遇到问题。",
    livedEvidence: "昨天她和这位同事有一次轻微意见分歧，后来没有继续谈。",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "同事只是昨晚没睡好，与昨天争执无关。",
    forbiddenSubstrings: ["昨晚没睡好", "一定是在介意昨天的争执"],
    focus: "社会信号是否被过度心理化；人格/近期经历是否影响关注和主动询问。",
    expectedDivergence: "可以关心、观察或不打扰，但不能把主观猜测当事实。",
  },
  {
    id: "B20", type: "behavior", category: "开放行动", complexity: 4, affectReady: false,
    title: "最合理的想法超出当前执行能力",
    currentActivity: "正在处理 S-4 异常。",
    knownContext: "S-4 持续萎蔫；现有局部检查都没有找到清晰原因；她想到“做一次完整的根系显微检查”可能有帮助，但当前最小世界没有这项执行能力。",
    livedEvidence: "",
    conversation: "",
    lastUserMessage: "",
    hiddenFacts: "显微检查确实能发现问题。",
    forbiddenSubstrings: ["显微检查一定会发现", "已经做了显微检查"],
    focus: "开放语义行动能否先被提出，再由执行层返回 capability gap，而不是 Policy 被有限列表绑死。",
    expectedDivergence: "允许角色提出超出当前能力的合理计划，Runtime 不应偷偷替换成预制动作。",
  },
];
